<?php
/**
 * Intebwio - Export and Sharing API
 * Exports pages in various formats and manages sharing
 */

header('Content-Type: application/json');

require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/Database.php';

class ExportManager {
    private $pdo;
    private $db;
    
    public function __construct($pdo) {
        $this->pdo = $pdo;
        $this->db = new Database($pdo);
    }
    
    /**
     * Export page to PDF
     */
    public function exportPDF($pageId) {
        try {
            $page = $this->db->getPageById($pageId);
            if (!$page) {
                return ['success' => false, 'message' => 'Page not found'];
            }
            
            // Generate file name
            $fileName = 'Intebwio_' . preg_replace('/[^a-zA-Z0-9_]/', '_', $page['search_query']) . '.pdf';
            
            // Return PDF generation instructions
            return [
                'success' => true,
                'format' => 'pdf',
                'page_id' => $pageId,
                'file_name' => $fileName,
                'size_estimate' => 'Calculated based on content'
            ];
        } catch (Exception $e) {
            return ['success' => false, 'message' => $e->getMessage()];
        }
    }
    
    /**
     * Export page to Markdown
     */
    public function exportMarkdown($pageId) {
        try {
            $page = $this->db->getPageById($pageId);
            if (!$page) {
                return ['success' => false, 'message' => 'Page not found'];
            }
            
            $markdown = "# " . $page['title'] . "\n\n";
            $markdown .= "*Generated by Intebwio on " . date('Y-m-d H:i:s') . "*\n\n";
            $markdown .= "## Overview\n\n";
            $markdown .= $page['description'] . "\n\n";
            
            if (!empty($page['search_results'])) {
                $markdown .= "## Sources\n\n";
                foreach ($page['search_results'] as $result) {
                    $markdown .= "### " . $result['title'] . "\n";
                    $markdown .= "- **Source:** " . $result['source_name'] . "\n";
                    $markdown .= "- **URL:** " . $result['source_url'] . "\n";
                    $markdown .= "- **Author:** " . $result['author'] . "\n";
                    $markdown .= "- **Relevance:** " . round(($result['relevance_score'] ?? 0) * 100) . "%\n";
                    $markdown .= "\n" . $result['description'] . "\n\n";
                }
            }
            
            return [
                'success' => true,
                'format' => 'markdown',
                'content' => $markdown
            ];
        } catch (Exception $e) {
            return ['success' => false, 'message' => $e->getMessage()];
        }
    }
    
    /**
     * Export to HTML
     */
    public function exportHTML($pageId) {
        try {
            $page = $this->db->getPageById($pageId);
            if (!$page) {
                return ['success' => false, 'message' => 'Page not found'];
            }
            
            return [
                'success' => true,
                'format' => 'html',
                'content' => $page['html_content']
            ];
        } catch (Exception $e) {
            return ['success' => false, 'message' => $e->getMessage()];
        }
    }
    
    /**
     * Create sharable link
     */
    public function createShareLink($pageId) {
        try {
            $shareToken = bin2hex(random_bytes(16));
            
            $stmt = $this->pdo->prepare("
                INSERT INTO share_links (page_id, share_token, shares_count)
                VALUES (?, ?, 0)
                ON DUPLICATE KEY UPDATE share_token = VALUES(share_token)
            ");
            
            $stmt->execute([$pageId, $shareToken]);
            
            $shareUrl = (isset($_SERVER['HTTPS']) ? 'https' : 'http') . '://' . 
                       $_SERVER['HTTP_HOST'] . '/page.php?share=' . $shareToken;
            
            return [
                'success' => true,
                'share_url' => $shareUrl,
                'share_token' => $shareToken
            ];
        } catch (Exception $e) {
            return ['success' => false, 'message' => $e->getMessage()];
        }
    }
    
    /**
     * Get share statistics
     */
    public function getShareStats($pageId) {
        try {
            $stmt = $this->pdo->prepare("
                SELECT 
                    share_token,
                    shares_count,
                    created_at,
                    last_accessed
                FROM share_links
                WHERE page_id = ?
            ");
            
            $stmt->execute([$pageId]);
            $link = $stmt->fetch();
            
            if (!$link) {
                return ['success' => false, 'message' => 'No share link found'];
            }
            
            return [
                'success' => true,
                'stats' => $link
            ];
        } catch (Exception $e) {
            return ['success' => false, 'message' => $e->getMessage()];
        }
    }
}

try {
    $action = isset($_GET['action']) ? $_GET['action'] : '';
    $exporter = new ExportManager($pdo);
    
    switch ($action) {
        case 'pdf':
            $pageId = intval($_GET['page_id'] ?? 0);
            if (!$pageId) {
                http_response_code(400);
                echo json_encode(['success' => false, 'message' => 'page_id required']);
                exit;
            }
            echo json_encode($exporter->exportPDF($pageId));
            break;
            
        case 'markdown':
            $pageId = intval($_GET['page_id'] ?? 0);
            if (!$pageId) {
                http_response_code(400);
                echo json_encode(['success' => false, 'message' => 'page_id required']);
                exit;
            }
            echo json_encode($exporter->exportMarkdown($pageId));
            break;
            
        case 'html':
            $pageId = intval($_GET['page_id'] ?? 0);
            if (!$pageId) {
                http_response_code(400);
                echo json_encode(['success' => false, 'message' => 'page_id required']);
                exit;
            }
            echo json_encode($exporter->exportHTML($pageId));
            break;
            
        case 'share':
            $pageId = intval($_GET['page_id'] ?? 0);
            if (!$pageId) {
                http_response_code(400);
                echo json_encode(['success' => false, 'message' => 'page_id required']);
                exit;
            }
            echo json_encode($exporter->createShareLink($pageId));
            break;
            
        case 'share_stats':
            $pageId = intval($_GET['page_id'] ?? 0);
            if (!$pageId) {
                http_response_code(400);
                echo json_encode(['success' => false, 'message' => 'page_id required']);
                exit;
            }
            echo json_encode($exporter->getShareStats($pageId));
            break;
            
        default:
            http_response_code(400);
            echo json_encode(['success' => false, 'message' => 'Unknown action']);
    }
    
} catch (Exception $e) {
    error_log("Export error: " . $e->getMessage());
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'message' => 'Server error'
    ]);
}

?>
